docs/developpement.md

feat(dev): add conventionalcomments.org

---

docs/_sidebar.md
docs/developpement.md
docs/securite.md
docs/standards.md

reprise des récentes recos ANSSI

feat: more security for #21

---

.gitlab-ci.yml
maintenance/tools/git-mirror-cleaner/.gitlab-ci.yml
maintenance/tools/git-mirror-cleaner/README.md
maintenance/tools/git-mirror-cleaner/bin/git-mirror-cleaner
maintenance/tools/git-mirror-cleaner/test/_helper.bash
maintenance/tools/git-mirror-cleaner/test/gmc_clean.bats
maintenance/tools/git-mirror-cleaner/test/gmc_compare_origin_mirror.bats
maintenance/tools/git-mirror-cleaner/test/gmc_get_remote_branches.bats
maintenance/tools/git-mirror-cleaner/test/gmc_remove_mirror_branch.bats
maintenance/tools/git-mirror-cleaner/test/gmc_reset.bats
maintenance/tools/git-mirror-cleaner/test/gmc_set_get.bats
maintenance/tools/git-mirror-cleaner/test/gmc_tmp.bats

feat(git-mirror-cleaner): initial commit

---

.gitlab-ci.yml
cron/.gitlab-ci.yml
cron/bains-douches/.gitlab-ci.yml
cron/bains-douches/README.md
cron/bains-douches/bin/bathing
cron/bains-douches/bin/job-template.jq
cron/bains-douches/jobs/socialgouv.yml
cron/bains-douches/test/_helper.bash
cron/bains-douches/test/bathing_get_projects.bats
cron/bains-douches/test/bathing_group_id.bats
cron/bains-douches/test/bathing_main.bats
cron/bains-douches/test/bathing_trasform_to_gitlab_jobs.bats
maintenance/tools/git-mirror-cleaner/.gitlab-ci.yml
maintenance/tools/git-mirror-cleaner/bin/git-mirror-cleaner

feat(cron): initial commit

---

cron/bains-douches/bin/bathing
cron/bains-douches/test/bathing_main.bats

fix(bains-douches): ignore traefigit

---

docs/_sidebar.md
docs/standards.md
docs/tests.md

initial doc for codecept/gherkin setup

feat(test): add codecept doc

---

docs/kubernetes.md

docs(k8s): add config variables section

---

docs/faq.md

fix(docs): next.js + build time variables

---

docs/faq.md

docs(faq): add backup job info

---

docs/kubernetes.md

doc: use /healthz for probes

---

docs/faq.md
docs/kubernetes.md

feat: add ingress info

---

docs/fonctionnement.md

Je propose de simplifier l'explication du fonctionnement
Et enlever le schéma qui ne reflète pas vraiment la réalité :)

fix: simpler functionnement

---

docs/kubernetes.md

Lien vers un TB article : https://sendilkumarn.com/blog/kubernetes-for-everyone/

docs(kubernetes): add kube intro link

---

docs/faq.md

Add howto create a sealed secret when dealing with private gitlab registry

docs: add private gitlab registry secret howto

---

docs/faq.md
docs/kubernetes.md

docs(faq): add some grafana infos

---

cron/bains-douches/bin/bathing

fix(bains-douches): update to yq@4.x

---

docs/faq.md

from https://gitlab.factory.social.gouv.fr/infra/documentation/-/issues/811 and https://gitlab.factory.social.gouv.fr/infra/documentation/-/issues/812

docs: add janitor rules

---

docs/_sidebar.md
docs/pra.md

document demandé par le startups

docs: add PRA/PCA

---

docs/kubernetes.md

Explain how to ensure a sealed-secret is valid before deploying

docs: add info about sealed-secret validation

---

docs/kubernetes.md

Je pense qu'on peut guider encore plus les devs, qui ne sont généralement pas les auteurs et autrices des fichiers de workflows (ou alors qui se sont fait aider par l'équipe SRE). Comme nous avons parfois besoin d'ajouter des sealed secrets, ça pourrait aider de suggérer ou chercher. En tout cas ça m'aurait aidé je pense !
À votre dispo pour en discuter.

docs(kubernetes): more about sealed secrets for prod

---

docs/databases.md

ajout d'une video FR intéressante sur le sujet des indexes https://www.youtube.com/watch?v=bo5j9xgiF48

docs(bdd): add videos on indexes

---

docs/securite.md

add default .talismanrc for JS example

docs(talisman): details

---

docs/_sidebar.md
docs/mobile.md
docs/standards.md

add basic mobile recos pour la doc technique

docs: add mobile

---

docusaurus.config.js

fix(docs): links

---

docs/standards/securite.md

docs(secu): add http headers recos

---

sidebars.js

Ajout des liens des différentes prezs

fix: add liens presentations

---

docs/standards/securite.md

Ajout d'une note sur le chiffrement de fichiers

docs(secu): add note about streaming-file-encryption

---

docs/infrastructure/disaster-recovery.md

fix: fix DR instructions

---

docs/faq.md
docs/init/presentation.md

Add teleport connection informations

Update connect database section

---

docs/faq.md

Suppression de la doc BASTION au profit de TELEPORT

docs: teleport adjustments

---

docs/standards/developpement.md
docs/standards/docker.md
docs/standards/kubernetes.md

ajout des tableaux de recommandations

Maj documentation

---

docs/standards/kubernetes.md
docs/standards/securite.md

docs: add log applicatifs
